apiVersion: v1
kind: Secret
metadata:
  name: {{ include "billing.fullname" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq.pass: {{ .Values.parameters.rabbit.pass | b64enc | quote }}
  readModel.pass: {{ .Values.parameters.readModel.pass | b64enc | quote }}
  writeModel.pass: {{ .Values.parameters.writeModel.pass | b64enc | quote }}
