apiVersion: v1
kind: Service
metadata:
  name: {{ include "billing.fullname" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9800
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "billing.selectorLabels" . | nindent 4 }}
