parameters:
  env: dev
  port: 8080
  log_level: info
  rabbit:
    host: api-rabbitmq
    user: guest
    pass: guest
  writeModel:
    host: api-postgresql
    user: postgres
    pass: changeme
  readModel:
    host: api-postgresql
    user: postgres
    pass: changeme

image:
  pullPolicy: IfNotPresent

autoscaling:
  api: 
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 75
  worker: 
    min: 1
    max: 5
    queue: events
    avgItems: 5

resources: 
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

prometheus-operator:
  enabled: true
  grafana:
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        billing-api:
          json: |
            {
              "editable": true,
              "gnetId": null,
              "graphTooltip": 0,
              "id": 26,
              "links": [],
              "panels": [
                {
                  "aliasColors": {},
                  "bars": false,
                  "dashLength": 10,
                  "dashes": false,
                  "datasource": null,
                  "fill": 1,
                  "fillGradient": 0,
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 0,
                    "y": 0
                  },
                  "hiddenSeries": false,
                  "id": 4,
                  "legend": {
                    "avg": false,
                    "current": false,
                    "max": false,
                    "min": false,
                    "show": true,
                    "total": false,
                    "values": false
                  },
                  "lines": true,
                  "linewidth": 1,
                  "nullPointMode": "null",
                  "options": {
                    "dataLinks": []
                  },
                  "percentage": false,
                  "pointradius": 2,
                  "points": false,
                  "renderer": "flot",
                  "seriesOverrides": [],
                  "spaceLength": 10,
                  "stack": false,
                  "steppedLine": false,
                  "targets": [
                    {
                      "expr": "sum(increase(transaction_create_success[5m]))",
                      "legendFormat": "Success",
                      "refId": "A"
                    },
                    {
                      "expr": "sum(increase(transaction_create_conflict[5m]))",
                      "legendFormat": "Conflict",
                      "refId": "B"
                    },
                    {
                      "expr": "sum(increase(transaction_create_error[5m]))",
                      "legendFormat": "Error",
                      "refId": "C"
                    }
                  ],
                  "thresholds": [],
                  "timeFrom": null,
                  "timeRegions": [],
                  "timeShift": null,
                  "title": "Transactions Created | Error",
                  "tooltip": {
                    "shared": true,
                    "sort": 0,
                    "value_type": "individual"
                  },
                  "type": "graph",
                  "xaxis": {
                    "buckets": null,
                    "mode": "time",
                    "name": null,
                    "show": true,
                    "values": []
                  },
                  "yaxes": [
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    },
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    }
                  ],
                  "yaxis": {
                    "align": false,
                    "alignLevel": null
                  }
                },
                {
                  "aliasColors": {},
                  "bars": false,
                  "dashLength": 10,
                  "dashes": false,
                  "datasource": null,
                  "fill": 1,
                  "fillGradient": 0,
                  "gridPos": {
                    "h": 11,
                    "w": 24,
                    "x": 0,
                    "y": 8
                  },
                  "hiddenSeries": false,
                  "id": 2,
                  "legend": {
                    "avg": false,
                    "current": false,
                    "max": false,
                    "min": false,
                    "show": true,
                    "total": false,
                    "values": false
                  },
                  "lines": true,
                  "linewidth": 1,
                  "nullPointMode": "null",
                  "options": {
                    "dataLinks": []
                  },
                  "percentage": false,
                  "pointradius": 2,
                  "points": false,
                  "renderer": "flot",
                  "seriesOverrides": [],
                  "spaceLength": 10,
                  "stack": false,
                  "steppedLine": false,
                  "targets": [
                    {
                      "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
                      "refId": "A"
                    }
                  ],
                  "thresholds": [],
                  "timeFrom": null,
                  "timeRegions": [],
                  "timeShift": null,
                  "title": "Performace",
                  "tooltip": {
                    "shared": true,
                    "sort": 0,
                    "value_type": "individual"
                  },
                  "type": "graph",
                  "xaxis": {
                    "buckets": null,
                    "mode": "time",
                    "name": null,
                    "show": true,
                    "values": []
                  },
                  "yaxes": [
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    },
                    {
                      "format": "short",
                      "label": null,
                      "logBase": 1,
                      "max": null,
                      "min": null,
                      "show": true
                    }
                  ],
                  "yaxis": {
                    "align": false,
                    "alignLevel": null
                  }
                }
              ],
              "schemaVersion": 22,
              "style": "dark",
              "tags": [],
              "templating": {
                "list": []
              },
              "time": {
                "from": "now-30m",
                "to": "now"
              },
              "timepicker": {
                "refresh_intervals": [
                  "5s",
                  "10s",
                  "30s",
                  "1m",
                  "5m",
                  "15m",
                  "30m",
                  "1h",
                  "2h",
                  "1d"
                ]
              },
              "timezone": "",
              "title": "billing-api",
              "uid": "-9QdPCjWk",
              "version": 1
            }
  prometheus:
    enabled: true
    prometheusOperator:
      createCustomResource: true
    serviceMonitor:
      selfMonitor: true
    prometheusSpec:
      retention: 2d
    additionalServiceMonitors:
    - name: billing-api
      selector:
        matchLabels:
          app.kubernetes.io/instance: api
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 10s
