parameters:
  env: dev
  port: 3000
  log_level: info
  rabbit:
    host: api-rabbitmq
    user: guest
    pass: guest
  writeModel:
    host: api-postgresql
    user: postgres
    pass: changeme
  readModel:
    host: api-postgresql
    user: postgres
    pass: changeme

image:
  pullPolicy: IfNotPresent

autoscaling:
  api: 
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 75
  worker: 
    min: 3
    max: 5
    queue: events
    avgItems: 5

resources: 
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

prometheus-operator:
  enabled: true