parameters:
  env: dev
  port: 8080
  log_level: info
  rabbit:
    host: api-rabbitmq
    user: guest
    pass: guest
  writeModel:
    host: api-postgresql
    user: postgres
    pass: changeme
  readModel:
    host: api-postgresql
    user: postgres
    pass: changeme

image:
  pullPolicy: IfNotPresent

autoscaling:
  api: 
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 75
  worker: 
    min: 1
    max: 5
    queue: events
    avgItems: 5

resources: 
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

prometheus-operator:
  enabled: true
  prometheus:
    enabled: true
    prometheusOperator:
      createCustomResource: true
    serviceMonitor:
      selfMonitor: true
    prometheusSpec:
      retention: 2d
    additionalServiceMonitors:
    - name: billing-api
      selector:
        matchLabels:
          app.kubernetes.io/instance: api
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 10s
